# ----------------------------------------
# Feign client and Hystryx properties
# ----------------------------------------
feign:
  hystrix:
    enabled: true
  client:
    config:
      amazon:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL
        service: ${AMAZON_SERVER_URL:https://completion.amazon.com}

#https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  threadpool:
    default:
      coreSize: 10
      maximumSize: 10
      #add extra capacity
      #This property sets the maximum queue size of the BlockingQueue implementation.
      #If you set this to -1 (default) then SynchronousQueue will be used, otherwise a positive value will be used with LinkedBlockingQueue
      maxQueueSize: 10000
      queueSizeRejectionThreshold: 10000
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


# ----------------------------------------
# Logging settings
# ----------------------------------------
logging:
  level:
    com:
      sellics: DEBUG


# ----------------------------------------
# Management
# ----------------------------------------
management:
  #TODO: delete in production mode
  trace:
    http:
      include: REQUEST_HEADERS, PRINCIPAL, RESPONSE_HEADERS, COOKIE_HEADERS, TIME_TAKEN
  endpoints:
    web:
      exposure:
        include: httptrace, info, health
  endpoint:
    health:
      show-details: always